# This workflow will build a MuleSoft project and deploy to CloudHub

name: Build and Deploy to Development

on:
  push:
    branches: [feature]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONNECTED_APP_CLIENT_ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
      CONNECTED_APP_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
      anypoint.platform.client_id: ${{ secrets.ANYPOINT_PLATFORM_CLIENT_ID_DEV}}
      anypoint.platform.client_secret: ${{ secrets.ANYPOINT_PLATFORM_CLIENT_SECRET_DEV}}

    
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Cache Depenedencies
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    
    - name: Build with maven
      run: mvn -B clean package -DskipMunitTests -Dmule.connectedAppClientId=${{ env.CONNECTED_APP_CLIENT_ID }} -Dmule.connectedAppClientSecret=${{ env.CONNECTED_APP_CLIENT_SECRET }} -s .maven/settings.xml
    
    